package:
  name: ta-lib
  version: !!str 0.4.9

source:
  fn: TA_Lib-0.4.9.tar.gz
  url: https://github.com/mrjbq7/ta-lib/archive/TA_Lib-0.4.9.tar.gz
  md5: f2f6ec8b7d552ff96d53d56ffb7b4e97

requirements:
  build:
    - python
    - cython
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  imports:
    - talib

about:
  home: http://github.com/mrjbq7/ta-lib
  license: BSD License
