package:
  name: ta-lib
  version: !!str 0.4.8

source:
  fn: releases
  url: https://github.com/mrjbq7/ta-lib/releases
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ta-lib = ta-lib:main
    #
    # Would create an entry point called ta-lib that calls ta-lib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  # imports:

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/mrjbq7/ta-lib
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
