{% set name = "TA-Lib" %}
{% set version = "0.4.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 948001ca61672b4eeef12a8cc9e8c59b

build:
  number: 0
  skip: true # [py<37 or not x86_64]
  include_recipe: False

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools_scm
    - cython
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - talib

about:
  home: http://github.com/mrjbq7/ta-lib
  license: BSD
