{% set data = load_setuptools() %}

package:
  name: zipline
  version: {{ GIT_DESCRIBE_TAG|replace('v', '') }}

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: np{{ NPY_VER|replace('.', '') }}py{{ PY_VER|replace('.', '') }}_{{ (
    GIT_BUILD_STR if GIT_DESCRIBE_NUMBER|int != 0 else '0'
  ) }}

source:
  git_url: ../../

requirements:
  build:
    - python {{ PY_VER }}*
    {% for req in data.get('build_requires', []) -%}
    - {{req}}
    {% endfor %}
  run:
    - python
    {% for req in data.get('install_requires', []) -%}
    - {{req}}
    {% endfor %}

test:
  {#  When we include the tests module in the zipline package, we can use this:
  requires:
    {% for req in data.get('extras_require', {}).get('dev', []) -%}
    - {{req}}
    {% endfor %}
  #}
  # Python imports
  imports:
    - zipline

about:
  home: https://zipline.io
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
