"""
factor.py
"""
from itertools import chain
import re
from operator import attrgetter

from six.moves import range

import numexpr
from numexpr.necompiler import getExprNames

from numpy import find_common_type
from zipline.modelling.computable import Term

_VARIABLE_NAME_RE = re.compile("^(x_)([0-9]+)$")
_NUMERIC_TYPES = (int, float, long)


_ops_to_right_bind_methods = {
    '+': '__radd__',
    '-': '__rsub__',
    '*': '__rmul__',
    '/': '__rdiv__',
    '**': '__rpow__',
}


def _bad_op(op, left, right):
    return TypeError(
        "Can't compute {left} {op} {right}".format(
            op=op,
            left=type(left).__name__,
            right=type(right).__name__,
        )
    )


def _factor_binops(op):
    """
    Factory function for making binary operator methods on Factor.

    Returns a pair of functions, binop and rbinop, suitable for implementing
    functions like __add__ and __radd__.
    """
    # When adding a factor to a NumericalExpression, we defer to the
    # right-binding implementation of the NumericalExpression operator.
    right_bind_method_getter = attrgetter(_ops_to_right_bind_methods[op])
    factor_op_factor_str = "x_0 %s x_1" % op

    def binop(self, other):
        if isinstance(other, NumericalExpression):
            # NumericalExpression overrides numerical ops to correctly handle
            # merging of inputs.  Look up and call the appropriate operator on
            # ourself.
            return right_bind_method_getter(other)(self)
        elif isinstance(other, Factor):
            return NumericalExpression(
                factor_op_factor_str,
                (self, other),
            )
        elif isinstance(other, _NUMERIC_TYPES):
            return NumericalExpression(
                "x_0 {op} {constant}".format(op=op, constant=other),
                binds=(self,),
            )
        raise _bad_op(op, self, other)

    def rbinop(self, other):
        # Only have to handle the numeric case because in all other valid cases
        # the corresponding left-binding method will be called.
        if isinstance(other, _NUMERIC_TYPES):
            return NumericalExpression(
                "{constant} {op} x_0".format(op=op, constant=other),
                binds=(self,),
            )
        raise _bad_op(op, other, self)

    return binop, rbinop


class Factor(Term):
    """
    A transformation yielding a timeseries of scalar values associated with an
    Asset.
    """
    # Autogenerated binary operators.
    __add__, __radd__ = _factor_binops('+')
    __sub__, __rsub__ = _factor_binops('-')
    __mul__, __rmul__ = _factor_binops('*')
    __div__, __rdiv__ = _factor_binops('/')
    __pow__, __rpow__ = _factor_binops('**')


def _ensure_element(tup, elem):
    """
    Create a tuple containing all elements of tup, plus elem.

    Returns the new tuple and the index of elem in the new tuple.
    """
    try:
        return tup, tup.index(elem)
    except ValueError:
        return tuple(chain(tup, (elem,))), len(tup)


def _numerical_expression_binops(op):
    """
    Factory function for making binary operator methods on NumericalExpression.

    Returns a pair of functions, binop and rbinop, suitable for implementing
    functions like __add__ and __radd__.
    """
    def binop(self, other):
        self_expr, other_expr, new_inputs = self._build_binop(op, other)
        return NumericalExpression(
            "({left}) {op} ({right})".format(
                left=self_expr,
                right=other_expr,
                op=op,
            ),
            new_inputs,
        )

    def rbinop(self, other):
        self_expr, other_expr, new_inputs = self._build_binop(op, other)
        return NumericalExpression(
            "({left}) {op} ({right})".format(
                left=other_expr,
                right=self_expr,
                op=op,
            ),
            new_inputs,
        )

    return binop, rbinop


class NumericalExpression(Factor):
    """
    Factor binding to a numexpr expression.

    Parameters
    ----------
    expr : string
       A string suitable for passing to numexpr.  All variables in 'expr'
       should be of the form "x_i", where i is the index of the corresponding
       factor input in 'binds'.
    binds : tuple
       A tuple of factors to use as inputs.
    """

    def __new__(cls, expr, binds):
        return super(NumericalExpression, cls).__new__(
            cls,
            inputs=binds,
            window_length=0,
            domain=None,
            dtype=find_common_type(
                [factor.dtype for factor in binds],
                [],
            ),
            expr=expr,
        )

    @classmethod
    def static_identity(cls, expr, *args, **kwargs):
        return (
            super(NumericalExpression, cls).static_identity(*args, **kwargs),
            expr,
        )

    def _init(self, expr, *args, **kwargs):
        self._expr = expr
        return super(NumericalExpression, self)._init(*args, **kwargs)

    def _validate(self):
        """
        Ensure that our expression string has variables of the form x_0, x_1,
        ... x_(N - 1), where N is the length of our inputs.
        """
        variable_names, _unused = getExprNames(self._expr, {})
        expr_indices = []
        for name in variable_names:
            match = _VARIABLE_NAME_RE.match(name)
            if not match:
                raise ValueError("%r is not a valid variable name" % name)
            expr_indices.append(int(match.group(2)))

        expr_indices.sort()
        expected_indices = list(range(len(self.inputs)))
        if expr_indices != expected_indices:
            raise ValueError(
                "Expected %s for variable indices, but got %s" % (
                    expected_indices, expr_indices,
                )
            )

    def compute_from_arrays(self, arrays, outbuf, dates, assets):
        # This writes directly into our output buffer.
        numexpr.evaluate(
            self._expr,
            local_dict={
                "x_%d" % idx: array
                for idx, array in enumerate(arrays)
            },
            global_dict={},
            out=outbuf,
        )

    def _rebind_variables(self, new_inputs):
        """
        Return self._expr with all variables rebound to the indices implied by
        new_inputs.
        """
        expr = self._expr
        for idx, input_ in enumerate(self.inputs):
            old_varname = "x_%d" % idx
            # Temporarily rebind to x_temp_N so that we don't overwrite the
            # same value multiple times.
            temp_new_varname = "x_temp_%d" % new_inputs.index(input_)
            expr = expr.replace(old_varname, temp_new_varname)
        # Clear out the temp variables now that we've finished iteration.
        return expr.replace("_temp_", "_")

    def _merge_expressions(self, other):
        """
        Merge the inputs of two NumericalExpressions into a single input tuple,
        rewriting their respective string expressions to make input names
        resolve correctly.

        Returns a tuple of (new_self_expr, new_other_expr, new_inputs)
        """
        new_inputs = tuple(set(self.inputs).union(other.inputs))
        new_self_expr = self._rebind_variables(new_inputs)
        new_other_expr = other._rebind_variables(new_inputs)
        return new_self_expr, new_other_expr, new_inputs

    def _build_binop(self, op, other):
        """
        Compute new expression strings and a new inputs tuple for combining
        self and other with a binary operator.
        """
        if isinstance(other, NumericalExpression):
            self_expr, other_expr, new_inputs = self._merge_expressions(other)
        elif isinstance(other, Factor):
            self_expr = self._expr
            new_inputs, other_idx = _ensure_element(self.inputs, other)
            other_expr = "x_%d" % other_idx
        elif isinstance(other, _NUMERIC_TYPES):
            self_expr = self._expr
            other_expr = str(other)
            new_inputs = self.inputs
        else:
            raise _bad_op(op, other)
        return self_expr, other_expr, new_inputs

    __add__, __radd__ = _numerical_expression_binops('+')
    __sub__, __rsub__ = _numerical_expression_binops('-')
    __mul__, __rmul__ = _numerical_expression_binops('*')
    __div__, __rdiv__ = _numerical_expression_binops('/')
    __pow__, __rpow__ = _numerical_expression_binops('**')


class TestFactor(Factor):
    """
    Base class for testing that asserts all inputs are correctly shaped.
    """

    def compute_from_windows(self, windows, outbuf, dates, assets):
        assert self.window_length > 0
        for idx, _ in enumerate(dates):
            result = self.from_windows(*(next(w) for w in windows))
            assert result.shape == (len(assets),)
            outbuf[idx] = result

        for window in windows:
            try:
                next(window)
            except StopIteration:
                pass
            else:
                raise AssertionError("window %s was not exhausted" % window)
        return outbuf

    def compute_from_arrays(self, arrays, outbuf, dates, assets):
        assert self.window_length == 0
        for array in arrays:
            assert array.shape == len(dates), len(assets) == outbuf.shape
        outbuf[:] = self.from_arrays(*arrays)
