package:
  name: intervaltree
  version: "2.1.0"

source:
  fn: intervaltree-2.1.0.tar.gz
  url: https://pypi.python.org/packages/source/i/intervaltree/intervaltree-2.1.0.tar.gz
  md5: 33bef3448aaf30b78aa093dc7c315c2c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - intervaltree = intervaltree:main
    #
    # Would create an entry point called intervaltree that calls intervaltree.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sortedcontainers

  run:
    - python
    - sortedcontainers

test:
  # Python imports
  imports:
    - intervaltree

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/chaimleib/intervaltree
  license: Apache Software License
  summary: 'Editable interval tree data structure for Python 2 and 3'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
