#!/usr/bin/env bash

# Consolidated installation script for use by both Travis and humans.

# First installs pip, then installs the project requirements,
# then editably installs zipline itself.

set -euvxo pipefail

echo
echo "Installing zipline using $(which python)"
echo

# see https://github.com/Blosc/bcolz/issues/398#issuecomment-698748897
export DISABLE_BCOLZ_AVX2=true
python -m pip install -U pip setuptools

# requirements.in have to be installed first so the following requirements
# can be compiled against their specific versions
python -m pip install -r etc/requirements_build.in
pip install git+https://github.com/stefan-jansen/bcolz.git --no-binary :all
python -m pip install -e .[all]

echo
echo "Installation complete! Try running 'zipline --help'."
echo
