package:
  name: cyordereddict
  version: "0.2.2"

source:
  fn: cyordereddict-0.2.2.tar.gz
  url: https://pypi.python.org/packages/source/c/cyordereddict/cyordereddict-0.2.2.tar.gz
  md5: 6279eb0bf9819f0293ad5315b2d484d0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cyordereddict = cyordereddict:main
    #
    # Would create an entry point called cyordereddict that calls cyordereddict.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - cyordereddict
    - cyordereddict.benchmark

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/shoyer/cyordereddict
  license: BSD License
  summary: "Cython implementation of Python's collections.OrderedDict"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
