#!/bin/sh
#
# An hook script to verify linting and passing unit tests.
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, copy or symlink to your repo's
# ".git/hooks/pre-commit".
#
# Please read the following as it will execute on your machine on each commit.

set -e

# Run flake8 linting
flake8 zipline tests
# Run unit tests
nosetests -x
