{% set name = "Logbook" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: Logbook-1.5.3.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 719970ea22dd274797bb4328161d700f


build:
  number: 0
  skip: true # [py<37 or not x86_64]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - logbook

about:
  home: https://logbook.readthedocs.io/en/stable/
  license: BSD
  summary: 'A logging replacement for Python'
