package:
  name: logbook
  version: "0.12.5"

source:
  fn: Logbook-0.12.5.tar.gz
  url: https://pypi.python.org/packages/source/L/Logbook/Logbook-0.12.5.tar.gz
  md5: 1bf64289b9b4cada5a61817c63dd9e82
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - logbook = logbook:main
    #
    # Would create an entry point called logbook that calls logbook.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six >=1.4.0

  run:
    - python
    - six >=1.4.0

test:
  # Python imports
  imports:
    - logbook

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://logbook.pocoo.org/
  license: BSD
  summary: 'A logging replacement for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
