package:
  name: lru-dict
  version: "1.1.4"

source:
  fn: lru-dict-1.1.4.tar.gz
  url: https://files.pythonhosted.org/packages/c3/b7/4e5bcbdfdc2227001f897051d6f4c83f9d236fe89a9df74da07cc3d9bac8/lru-dict-1.1.4.tar.gz
  md5: 95ed142416b32c4b03dd8e7dae924f38
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - lru-dict = lru-dict:main
    #
    # Would create an entry point called lru-dict that calls lru-dict.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - lru

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/amitdev/lru-dict
  license: MIT License
  summary: 'A fast and memory efficient LRU cache.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml