{% set name = "requests" %}
{% set version = "2.20.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "ea881206e59f41dbd0bd445437d792e43906703fff75ca8ff43ccdb11f33f263" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - chardet >=3.0.2,<3.1.0
    - idna >=2.5,<2.8
    - urllib3 >=1.21.1,<1.25
    - certifi >=2017.4.17
  run:
    - python
    - chardet >=3.0.2,<3.1.0
    - idna >=2.5,<2.8
    - urllib3 >=1.21.1,<1.25
    - certifi >=2017.4.17

test:
  imports:
    - requests
#  requires:
#    - pysocks >=1.5.6,!=1.5.7
#    - pytest >=2.8.0
#    - pytest-cov
#    - pytest-httpbin ==0.0.7
#    - pytest-mock
#    - pytest-xdist

about:
  home: http://python-requests.org
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: Python HTTP for Humans.
  description: "Requests: HTTP for Humans"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
