package:
  name: numexpr
  version: "2.4.6"

source:
  fn: numexpr-2.4.6.tar.gz
  url: https://pypi.python.org/packages/source/n/numexpr/numexpr-2.4.6.tar.gz
  md5: 17ac6fafc9ea1ce3eb970b9abccb4fbd

requirements:
  build:
    - python
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  # Python imports
  imports:
    - numexpr
