{% set name = "iso4217" %}
{% set version = "1.6.20180829" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 33f404b5eeb3cb8572f132b7c697782eccffeb00630900f305244ffa058e875c

build:
  number: 0
  script: "python -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - iso4217

about:
  home: "https://github.com/dahlia/iso4217"
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file:
  summary: "ISO 4217 currency data package for Python"
  doc_url:
  dev_url:

extra:
  recipe-maintainers: ''
