{% set name = "empyrical" %}
{% set version = "0.4.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fcb65ae26a38cab34458b3fde5e149c7966e61aebcdbaae9cd3355a0d41f7578" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9.2
    - pandas >=0.16.1
    - scipy >=0.15.1
    - pandas-datareader >=0.2
    - bottleneck >=1.0.0
  run:
    - python
    - numpy >=1.9.2
    - pandas >=0.16.1
    - scipy >=0.15.1
    - pandas-datareader >=0.2
    - bottleneck >=1.0.0

test:
  imports:
    - empyrical
    - empyrical.tests
  requires:
    - nose >=1.3.7
    - parameterized >=0.6.1

about:
  home: https://github.com/quantopian/empyrical
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: empyrical is a Python library with performance and risk statistics commonly used in quantitative finance
  description: 'empyrical is a Python library with performance and risk

    statistics commonly used in quantitative finance by `Quantopian Inc`_.


    .. _Quantopian Inc: https://www.quantopian.com

    .. _Zipline: http://zipline.io

    .. _pyfolio: http://quantopian.github.io/pyfolio/

    '
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
