package:
  name: empyrical
  version: "0.1.11"

source:
  fn: empyrical-0.1.11.tar.gz
  url: https://pypi.python.org/packages/df/82/c4050b0fe341db97430b2de7ae736d89a2ddb78636d3e0235aef1b7499d5/empyrical-0.1.11.tar.gz
  md5: fbd543416d204688146f13f325ca8731

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - pandas >=0.16.1
    - scipy >=0.15.1
    - bottleneck >=1.0.0

  run:
    - python
    - numpy x.x
    - pandas >=0.16.1
    - scipy >=0.15.1
    - bottleneck >=1.0.0


about:
  home: https://github.com/quantopian/empyrical
  license: Apache Software License
  summary: 'empyrical is a Python library with performance and risk statistics\ncommonly used in quantitative finance'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
