package:
  name: empyrical
  version: "0.1.10"

source:
  fn: empyrical-0.1.10.tar.gz
  url: https://pypi.python.org/packages/2c/b4/658f06c8bc05f847e9ccd6b8131e6e4589bbeb875e239d568a821fd1babc/empyrical-0.1.10.tar.gz
  md5: cf4439bad083150639ae5b27698c64d4


requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - pandas >=0.16.1
    - scipy >=0.15.1
    - bottleneck >=1.0.0

  run:
    - python
    - numpy x.x
    - pandas >=0.16.1
    - scipy >=0.15.1
    - bottleneck >=1.0.0


about:
  home: https://github.com/quantopian/empyrical
  license: Apache Software License
  summary: 'empyrical is a Python library with performance and risk statistics\ncommonly used in quantitative finance'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
