{% set name = "bcolz-zipline" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bcolz-zipline-{{ version }}.tar.gz
  sha256: f04a15ecc312c91604d463a3e64f9f64b2623b766bc03fc4f7b159d8f2e71856

build:
  number: 0
  skip: true   # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools-scm
    - toml
  run:
    - numpy
    - python

test:
  imports:
    - bcolz
    - bcolz.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stefan-jansen/bcolz-zipline
  summary: Columnar and compressed data containers.
  license: BSD-1-Clause
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - stefan-jansen
