{% set name = "bcolz" %}
{% set version = "0.12.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a8dafa42cd4f3ca130ecb81f7e778204a12c2180c18fd570ef753de58ee7ddbd" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >1.5.4
    - numpy x.x
    - numpy >=1.7
    - cython >=0.22
  run:
    - python
    - numpy x.x
    - numpy >=1.7

test:
  imports:
    - bcolz
    - bcolz.tests
  requires:
    - mock
    - unittest2 # [py26]

about:
  home: https://github.com/Blosc/bcolz
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: columnar and compressed data containers.
  description: 'bcolz provides columnar and compressed data containers.  Column

    storage allows for efficiently querying tables with a large number of

    columns.  It also allows for cheap addition and removal of column.  In

    addition, bcolz objects are compressed by default for reducing

    memory/disk I/O needs.  The compression process is carried out

    internally by Blosc, a high-performance compressor that is optimized

    for binary data.'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
