# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "2.2.2.dev41+dirty"
__version_tuple__ = version_tuple = (2, 2, 2, "dev41", "dirty")
