{% set name = "trading-calendars" %}
{% set version = "1.11.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "76ec1d28f27f769969ae532942025d319a6acee4d1e664651e3f4a07440ce185" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  # NOTE: the name of the pypi package is trading-calendars,
  # but in the list of sources for packages, the hyphen is
  # converted to an underscore
  url: https://pypi.io/packages/source/t/trading_calendars/trading_calendars-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - lru-dict
    - numpy
    - pandas
    - pytz
    - toolz
  run:
    - python
    - lru-dict
    - numpy
    - pandas
    - pytz
    - toolz

test:
  imports:
    - trading_calendars
    - trading_calendars.utils

about:
  home: https://github.com/quantopian/trading_calendars
  license: Apache Software
  license_family: APACHE
  license_file: ''
  summary: trading_calendars is a Python library with securities exchange calendars used by Quantopian's Zipline.
  description: "trading_calendars is a Python library with\nsecurities exchange calendars used by Quantopian's Zipline.\n\n.. _Quantopian Inc: https://www.quantopian.com\n.. _Zipline: http://zipline.io\n\
    \n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
